name: Build SDL

on:
  workflow_call:
    inputs:
      version:
        description: "SDL version"
        required: true
        type: string

jobs:
  build-windows:
    name: Download Windows
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          arch: [x64, x86, arm64]

    steps:
      - name: Cache
        uses: actions/cache@v4
        id: cache-windows
        with:
          path: SDL3.dll
          key: sdl-windows-${{ inputs.version }}-${{ matrix.arch }}
      - name: Download release build
        if: steps.cache-windows.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/libsdl-org/SDL/releases/download/release-${{ inputs.version }}/SDL3-${{ inputs.version }}-win32-${{ matrix.arch }}.zip
          unzip SDL3-${{ inputs.version }}-win32-${{ matrix.arch }}.zip SDL3.dll
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with: 
            name: sdl-windows-${{ matrix.arch }}
            path: SDL3.dll

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    container: registry.gitlab.steamos.cloud/steamrt/sniper/sdk:beta
    defaults:
      run:
        working-directory: SDL
    steps:
      - name: Clone SDL3
        working-directory: .
        run: git clone --depth 1 --branch release-${{ inputs.version }} https://github.com/libsdl-org/SDL.git
      - name: Configure
        run: >
          cmake -G Ninja
          -DCMAKE_BUILD_TYPE=Release
          -DSDL_SHARED=ON
          -DSDL_STATIC=OFF
          -DSDL_DISABLE_INSTALL=ON
          -DSDL_DISABLE_INSTALL_DOCS=ON
          -DSDL_INSTALL_TESTS=OFF
          -S . -B build
      - name: Build
        run: cmake --build build --config Release
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with: 
            name: sdl-linux
            path: SDL/build/*.so.0

  build-macos:
    name: Build MacOS (${{ matrix.arch }})
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
          arch: [arm64, x86_64]
    defaults:
      run:
        working-directory: SDL
    steps:
      - name: Set up Ninja
        uses: aseprite/get-ninja@main
      - name: Clone SDL3
        working-directory: .
        run: git clone --depth 1 --branch release-${{ inputs.version }} https://github.com/libsdl-org/SDL.git
      - name: Configure
        run: >
          cmake -G "Ninja"
          -DCMAKE_OSX_ARCHITECTURES="${{ matrix.arch }}"
          -DCMAKE_BUILD_TYPE=Release
          -DSDL_SHARED=ON
          -DSDL_STATIC=OFF
          -DSDL_DISABLE_INSTALL=ON
          -DSDL_DISABLE_INSTALL_DOCS=ON
          -DSDL_INSTALL_TESTS=OFF
          -DSDL_TESTS=false
          -DSDL_CLANG_TIDY=false \
          -S . -B build
      - name: Build
        run: cmake --build build --config Release
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with: 
            name: sdl-apple-macOS-${{ matrix.arch }}
            path: SDL/build/Release/*.dylib
