name: Build SDL_ttf

on:
  workflow_call:
    inputs:
      version:
        description: "SDL_ttf version"
        required: true
        type: string

jobs:
  build-windows:
    name: Download Windows
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          arch: [x64, x86, arm64]
    steps:
      - name: Cache
        uses: actions/cache@v4
        id: cache-windows
        with:
          path: SDL3_ttf.dll
          key: sdl-ttf-windows-${{ inputs.version }}-${{ matrix.arch }}
      - name: Download release build
        if: steps.cache-windows.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/libsdl-org/SDL_ttf/releases/download/release-${{ inputs.version }}/SDL3_ttf-${{ inputs.version }}-win32-${{ matrix.arch }}.zip
          unzip SDL3_ttf-${{ inputs.version }}-win32-${{ matrix.arch }}.zip SDL3_ttf.dll
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with: 
            name: sdl-ttf-windows-${{ matrix.arch }}
            path: SDL3_ttf.dll

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    # container: registry.gitlab.steamos.cloud/steamrt/sniper/sdk:latest
    defaults:
      run:
        working-directory: SDL_ttf
    steps:
      - name: Set up Ninja
        uses: aseprite/get-ninja@main
      - name: Set up SDL
        uses: libsdl-org/setup-sdl@main
        id: sdl
        with:
          cmake-generator: Ninja
          version: 3-head
          shell: sh
      - name: Set up Linux dependencies
        working-directory: .
        run: |
          sudo apt-get update
          sudo apt-get -y install \
            cmake \
            file \
            fonts-dejavu-core \
            libfreetype-dev \
            libharfbuzz-dev \
            pkg-config \
            ${NULL+}
      - name: Clone SDL_ttf
        working-directory: .
        run: git clone --recurse-submodules --branch release-${{ inputs.version }} https://github.com/libsdl-org/SDL_ttf.git
      - name: Check that versioning is consistent
        # We only need to run this once: arbitrarily use the Linux build
        run: ./build-scripts/test-versioning.sh
      - name: Configure
        run: >
          cmake -G Ninja
          -DCMAKE_POSITION_INDEPENDENT_CODE=ON
          -DBUILD_SHARED_LIBS=ON
          -DSDLTTF_HARFBUZZ=ON
          -DSDLTTF_WERROR=ON
          -DCMAKE_BUILD_TYPE=Release
          -DSDL_SHARED=ON
          -DSDL_STATIC=OFF
          -DSDL_DISABLE_INSTALL=ON
          -DSDL_DISABLE_INSTALL_DOCS=ON
          -DSDL_INSTALL_TESTS=OFF
          -DSDLTTF_INSTALL_MAN=OFF
          -DSDLTTF_VENDORED=ON
          -S . -B build
      - name: Build
        run: cmake --build build --config Release
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with: 
            name: sdl-ttf-linux
            path: SDL_ttf/build/*.so.0

  build-macos:
    name: Build MacOS (${{ matrix.arch }})
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
          arch: [arm64, x86_64]
    defaults:
      run:
        working-directory: SDL_ttf
    steps:
      - name: Set up Ninja
        uses: aseprite/get-ninja@main
      - name: Set up SDL
        id: sdl
        uses: libsdl-org/setup-sdl@main
        with:
          cmake-generator: Ninja
          cmake-arguments: |
            -DCMAKE_OSX_ARCHITECTURES="${{ matrix.arch }}" \
            -DSDL_DISABLE_INSTALL_DOCS=ON \
            -DSDL_INSTALL_TESTS=OFF
          version: 3-head
          shell: sh
      - name: Setup MacOS dependencies
        working-directory: .
        run: |
            brew install \
              freetype \
              harfbuzz \
              ${NULL+}
      - name: Clone SDL_ttf
        working-directory: .
        run: git clone --recurse-submodules --branch release-${{ inputs.version }} https://github.com/libsdl-org/SDL_ttf.git
      - name: Configure
        run: >
          cmake -G Ninja
          -DCMAKE_POLICY_VERSION_MINIMUM=3.5
          -DBUILD_SHARED_LIBS=ON
          -DCMAKE_OSX_ARCHITECTURES="${{ matrix.arch }}"
          -DCMAKE_POSITION_INDEPENDENT_CODE=ON
          -DSDLTTF_HARFBUZZ=ON
          -DSDLTTF_WERROR=ON
          -DCMAKE_BUILD_TYPE=Release
          -DSDL_SHARED=ON
          -DSDL_STATIC=OFF
          -DSDL_DISABLE_INSTALL=ON
          -DSDL_DISABLE_INSTALL_DOCS=ON
          -DSDL_INSTALL_TESTS=OFF
          -DSDLTTF_INSTALL_MAN=OFF
          -DSDLTTF_VENDORED=ON
          -DCMAKE_INSTALL_PREFIX=prefix_cmake
          -S . -B build
      - name: Build
        run: cmake --build build --config Release
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with: 
            name: sdl-ttf-apple-macOS-${{ matrix.arch }}
            path: SDL_ttf/build/*.dylib
